version: '3'

services:
  reverseproxy:
    build: ./nginx/
    ports:
      - 80:80
    depends_on:
      - service1
      - service2
    container_name: reverse

  service1:
    build: ./service1/
    ports: 
      - 6060:80
    container_name: service1
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

  service2:
    build: ./service2/
    ports:
      - 9090:80
    container_name: service2
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M